- name: download openssl tar.gz
  get_url: url=http://www.openssl.org/source/openssl-{{ openssl_version }}.tar.gz dest={{ lib_src_dir }}
  register: wget_openssl
- name: unpack openssl tar.gz
  command: tar zxf openssl-{{ openssl_version }}.tar.gz chdir={{ lib_src_dir }}
  when: wget_openssl.changed
- name: git clone headers-more module
  git: repo=https://github.com/agentzh/headers-more-nginx-module.git
    dest={{ lib_src_dir }}/headers-more-nginx-module
    version={{ headers_more_module_version }}
- name: download pcre
  get_url: url=ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-{{ pcre_version }}.tar.gz dest={{ lib_src_dir }}
  register: wget_pcre
- name: unpack pcre tar.gz
  command: tar zxf pcre-{{ pcre_version }}.tar.gz chdir={{ lib_src_dir }}
  when: wget_pcre.changed
- name: download nginx tar.gz
  get_url: url=http://nginx.org/download/nginx-{{ nginx_version }}.tar.gz dest={{ lib_src_dir }}
  register: wget_nginx
- name: unpack nginx tar.gz
  command: tar zxf nginx-{{ nginx_version }}.tar.gz chdir={{ lib_src_dir }}
  when: wget_nginx.changed
- include: compile_nginx.yml
  when: wget_nginx.changed
- name: start nginx
  command: "{{ nginx_symlink_path }}/sbin/nginx"
  sudo: true
