development:
  sessions:
    default:
      database: edo_pc_dev
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
  options:
    include_root_in_json: true
    include_type_for_serialization: true
    preload_models: false
#    protect_sensitive_fields: true
    raise_not_found_error: true
    scope_overwrite_exception: true
    use_activesupport_time_zone: true
    use_utc: false

test:
  sessions:
    default:
      database: edo_pc_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
