- name: install gems
  command: bundle install --path vendor/bundle chdir={{ app_root }}
- name: create mongoid.yml
  template: src=mongoid.yml.j2 dest={{ app_root }}/config/mongoid.yml
- name: create index
  command: bundle exec rake db:mongoid:create_indexes RAILS_ENV=development chdir={{ app_root }}
